src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>CurrentLinkedHeadquarters__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sede asociada</label>
        <referenceTo>Headquarters__c</referenceTo>
        <relationshipLabel>Empleados</relationshipLabel>
        <relationshipName>Empleados</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonalAbsencesId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ausencia</label>
        <referenceTo>PersonalAbsences__c</referenceTo>
        <relationshipLabel>Empleados</relationshipLabel>
        <relationshipName>Empleados</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Empleado</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Número de empleado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empleados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Headquarters__c.object
<CustomObject>
    <label>Sede</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sedes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HolidaysByHeadquarters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>HeadquartersName__c</fullName>
        <label>Sede</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HolidayDate__c</fullName>
        <label>Fecha</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Festivos por sedes</label>
</CustomObject>

src/objects/MonthlyTimeRecordControl__c.object
<CustomObject>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <label>Empleado viculado</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Registros de control mensuales</relationshipLabel>
        <relationshipName>MonthlyTimeRecordControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RangeEnd__c</fullName>
        <label>Fin de periodo</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RangeStart__c</fullName>
        <label>Inicio de periodo</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Registro de control mensual</label>
    <nameField>
        <displayFormat>RCM-{0000}</displayFormat>
        <label>Número de registro de control mensual</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de control mensuales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PersonalAbsences__c.object
<CustomObject>
    <fields>
        <fullName>AbsenceStart__c</fullName>
        <label>Inicio del permiso</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Ausencia</label>
    <nameField>
        <displayFormat>AUS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ausencias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TimeRecordControl__c.object
<CustomObject>
    <fields>
        <fullName>LaunchFinish__c</fullName>
        <label>Fin de comida</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LaunchStart__c</fullName>
        <label>Inicio de comida</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>RecordDate__c</fullName>
        <label>Fecha de registro</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estado del registro</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aceptado</fullName>
                </value>
                <value>
                    <fullName>Fraudulento</fullName>
                </value>
                <value>
                    <fullName>Inspeccionar</fullName>
                </value>
                <value>
                    <fullName>Contencioso</fullName>
                </value>
                <value>
                    <fullName>Resuelto Recursos Humanos</fullName>
                </value>
                <value>
                    <fullName>Resuelto Inspección</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeRecordControlId__c</fullName>
        <label>Registro de control mensual</label>
        <referenceTo>MonthlyTimeRecordControl__c</referenceTo>
        <relationshipLabel>Registros de control</relationshipLabel>
        <relationshipName>TimeRecordControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isTeleworking__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Teletrabajo</label>
        <type>Checkbox</type>
    </fields>
    <label>Registro de control</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Referencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de control</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchMultiTasks.cls
/**
 * @file        BatchReprocessLeadDigital.apxc
 * @author      Héctor Cervera Panella
 * @date        02/12/2019
 * @description AutoScheduled batch to:
 *              Create month time record controls 
 *              Create time record controls
 *              Inform non supervenue absences including holidays
 */
global class BatchMultiTasks implements Database.Batchable<sObject>, Database.Stateful{

    // Vars
	private static List<Employee__c> lstEmployees;
    private static List<TimeRecordControl__c> lstTimeRec;
    private static List<MonthlyTimeRecordControl__c> lstMonTimeRec;
    private static Date insDate = Date.today();
    private Map<Integer,Integer> mapDaysByMonth;

    private Integer CRON_INTERVAL;
    private Integer CRON_INTERVAL_WEEK;
	private Integer BATCH_SIZE;
	private Integer QUERY_LIMIT;

    // Builder
	global BatchMultiTasks(){
        CRON_INTERVAL = 10;
        BATCH_SIZE = 200;
        QUERY_LIMIT = 2500;
        CRON_INTERVAL_WEEK = 10080;
    }

    // Start
    global List<Employee__c> start(Database.BatchableContext BC) {
        
        lstEmployees = new List<Employee__c>([SELECT Id, PersonalAbsencesId__c, PersonalAbsencesId__r.ApprovedByHHRR__c, PersonalAbsencesId__r.AbsenceStart__c, 
                        PersonalAbsencesId__r.AbsenceEnd__c, PersonalAbsencesId__r.DailyAbsenceRangeNotSupervening__c, CurrentLinkedHeadquarters__r.Name
                        FROM Employee__c 
                        WHERE PersonalAbsencesId__c  =:null OR PersonalAbsencesId__r.AbsenceEnd__c > : insDate
                        LIMIT : QUERY_LIMIT]);
                                          
        List<Id> lstIdEmployees = getId(lstEmployees);
        Map<Integer,Integer> mapDaysByMonth = getDaysByMonth();
        lstMonTimeRec = new List<MonthlyTimeRecordControl__c>([SELECT Id, RangeStart__c, RangeEnd__c, EmployeeId__c
                        FROM MonthlyTimeRecordControl__c 
                        WHERE EmployeeId__c 
                        IN : lstIdEmployees 
                        AND RangeEnd__c  > :insDate
                        LIMIT : QUERY_LIMIT]);
        return lstEmployees;  
    }

    // Execute
    global void execute(Database.BatchableContext BC, List<Employee__c> lstEmployees){
        
		List<MonthlyTimeRecordControl__c> lstMonthTimeRecToCreate = new List<MonthlyTimeRecordControl__c>();
        List<TimeRecordControl__c> lstTimeRecToCreate = new List<TimeRecordControl__c>();
      
        List<HolidaysByHeadquarters__c> lstCs = HolidaysByHeadquarters__c.getAll().values();
        Date dat;
        Date datMonthly;
        Date dat1 = insDate;
        Date dat2 = insDate.addDays(1);
        Date dat3 = insDate.addDays(2);
        Date dat4 = insDate.addDays(3);
        Date dat5 = insDate.addDays(4);
        Date dat6 = insDate.addDays(5);
        Date dat7 = insDate.addDays(6);

        // Create new MonthlyTimeRecordControl__c in case of mmonth change and assign them to all employees
        for(MonthlyTimeRecordControl__c monIns: lstMonTimeRec){
            if(dat1.month()!=dat7.month()){
                if(dat1.month()!=dat3.month()){
                    datMonthly = dat3;
                }else if(dat1.month()!=dat4.month()){
                    datMonthly = dat4;
                }else if(dat1.month()!=dat5.month()){
                    datMonthly = dat5;
                }else if(dat1.month()!=dat6.month()){
                    datMonthly = dat6;
                }else{
                    datMonthly = dat7;
                }
                // Generate MonthlyTimeRecordControl__c starting value of datMonthly and assign to all employees
                for(Employee__c empMonthly: lstEmployees){
                    MonthlyTimeRecordControl__c monthTimeRec = new MonthlyTimeRecordControl__c();
                    monthTimeRec.EmployeeId__c = empMonthly.Id;
                    monthTimeRec.RangeStart__c = datMonthly;
                    monthTimeRec.RangeEnd__c = Date.valueOf(mapDaysByMonth.get(datMonthly.month()));
                    lstMonthTimeRecToCreate.add(monthTimeRec);
                }
            }
        }
        
        insert lstMonthTimeRecToCreate;
		
        // Inform holidays
        for(HolidaysByHeadquarters__c insCS: lstCs){
            for(Employee__c emp: lstEmployees){
                if((emp.CurrentLinkedHeadquarters__r.Name.contains(insCS.HeadquartersName__c) || insCS.HeadquartersName__c == 'Nacional' &&
                    insDate >= Date.valueOf(insCS.HolidayDate__c) && insDate <=Date.valueOf(insCS.HolidayDate__c).addDays(4))){
                        
                    if(Date.valueOf(insCS.HolidayDate__c) == insDate){
                        dat = dat1;
                    }else if(Date.valueOf(insCS.HolidayDate__c) == dat2){
                        dat = dat2;
                    }else if(Date.valueOf(insCS.HolidayDate__c) == dat3){
                        dat = dat3;
                    }else if(Date.valueOf(insCS.HolidayDate__c) == dat4){
                        dat = dat4;
                    }else{
                        dat = dat5;
                    }
                }

                TimeRecordControl__c timeRecIns = new TimeRecordControl__c();              
                timeRecIns.RecordDate__c = dat;
                timeRecIns.isTeleworking__c = true;
                timeRecIns.Status__c = 'Aceptado';
                timeRecIns.StartWorkingTime__c = Time.newInstance(08, 00, 0, 0);
                timeRecIns.EndWorkingTime__c = Time.newInstance(17, 00, 0, 0);
                timeRecIns.BreakStart__c = Time.newInstance(11, 00, 0, 0);
                timeRecIns.BreakEnd__c = Time.newInstance(11, 15, 0, 0);               
                timeRecIns.LaunchStart__c = Time.newInstance(14, 00, 0, 0);
                timeRecIns.LaunchFinish__c = Time.newInstance(15, 00, 0, 0);
                for(MonthlyTimeRecordControl__c insMTRC : lstMonTimeRec){
                    for(MonthlyTimeRecordControl__c insMTRC2 : lstMonthTimeRecToCreate){
                    	if(insMTRC.EmployeeId__c == emp.Id){
                        	timeRecIns.TimeRecordControlId__c = insMTRC.EmployeeId__c;
                        }else if(insMTRC2.EmployeeId__c == emp.Id){
                            timeRecIns.TimeRecordControlId__c = insMTRC2.EmployeeId__c;
                        }
                	}
            	}
                lstTimeRecToCreate.add(timeRecIns);
        	}
        }
        
        // Inform non supervenue absences
        for(Employee__c emp: lstEmployees){
            if((emp.PersonalAbsencesId__c!= null && emp.PersonalAbsencesId__r.ApprovedByHHRR__c == true && 
                insDate >= Date.valueOf(emp.PersonalAbsencesId__r.AbsenceEnd__c) && 
                insDate <=Date.valueOf(emp.PersonalAbsencesId__r.AbsenceStart__c).addDays(4))){
                
                Date datAbsenceStart = Date.valueOf(emp.PersonalAbsencesId__r.AbsenceStart__c);
                Date datAbsenceEnd = Date.valueOf(emp.PersonalAbsencesId__r.AbsenceEnd__c);
                Integer numberAbsenceDaysWeek;

                if(datAbsenceStart<=insDate){
                    numberAbsenceDaysWeek = datAbsenceEnd.daysBetween(insDate)>5 ? 5 : datAbsenceEnd.daysBetween(insDate);
                }else{
                    numberAbsenceDaysWeek = datAbsenceEnd.daysBetween(datAbsenceStart)>4? 4: datAbsenceEnd.daysBetween(datAbsenceStart);
                }
                for(Integer i=0; i<=numberAbsenceDaysWeek; i++){
                    TimeRecordControl__c timeRecIns = new TimeRecordControl__c();              
                    timeRecIns.RecordDate__c = dat;
                    timeRecIns.isTeleworking__c = true;
                    timeRecIns.Status__c = 'Aceptado';
                    timeRecIns.StartWorkingTime__c = Time.newInstance(08, 00, 0, 0);
                    timeRecIns.EndWorkingTime__c = Time.newInstance(17, 00, 0, 0);
                    timeRecIns.BreakStart__c = Time.newInstance(11, 00, 0, 0);
                    timeRecIns.BreakEnd__c = Time.newInstance(11, 15, 0, 0);               
                    timeRecIns.LaunchStart__c = Time.newInstance(14, 00, 0, 0);
                    timeRecIns.LaunchFinish__c = Time.newInstance(15, 00, 0, 0);
                    for(MonthlyTimeRecordControl__c insMTRC : lstMonTimeRec){
                        for(MonthlyTimeRecordControl__c insMTRC2 : lstMonthTimeRecToCreate){
                            if(insMTRC.EmployeeId__c == emp.Id){
                                timeRecIns.TimeRecordControlId__c = insMTRC.EmployeeId__c;
                            }else if(insMTRC2.EmployeeId__c == emp.Id){
                                timeRecIns.TimeRecordControlId__c = insMTRC2.EmployeeId__c;
                            }
                        }
                    }
                    lstTimeRecToCreate.add(timeRecIns);
                }
            }
        }
        insert lstTimeRecToCreate;
    } 


    // Finish
    global void finish(Database.BatchableContext BC){
        if (!Test.isRunningTest()) {
            DateTime currDayTime = System.now();
            System.debug(LoggingLevel.INFO,'Current DateTime is: '+currDayTime);
            Integer currHour = currDayTime.hour();
            System.debug(LoggingLevel.INFO,'Current Hour is: '+currHour);
            if(currHour==07){
                scheduleMe(CRON_INTERVAL_WEEK, BATCH_SIZE);
            }else{
                scheduleMe(CRON_INTERVAL, BATCH_SIZE);
            }
		}
    }

    // Util methods
    private static List<Id> getId(List<Employee__c> lstEmployeeIns){
        List<Id> lstIds = new List<Id>();

        if(!lstEmployeeIns.isEmpty()){
            for(Employee__c insEmp: lstEmployeeIns){
                lstIds.add(insEmp.Id);
            }
        }

        return lstIds;
    }

    private static Map<Integer, Integer> getDaysByMonth(){
        Map<Integer,Integer> toReturn = new Map<Integer,Integer>();

        toReturn.put(1,31);
        toReturn.put(2,28);
        toReturn.put(3,31);
        toReturn.put(4,30);
        toReturn.put(5,31);
        toReturn.put(6,30);
        toReturn.put(7,31);
        toReturn.put(8,31);
        toReturn.put(9,30);
        toReturn.put(10,31);
        toReturn.put(11,30);
        toReturn.put(12,31);

        return toReturn;
    }

    private static void scheduleMe(Integer interval, Integer batchSize) {
		System.scheduleBatch(new BatchMultiTasks(), Test.isRunningTest() ? 'ScheduleTestBatchMultiTasks' : 'BatchMultiTasks', interval, batchSize);
	}
    
}