src/objects/Employee__c.object
<CustomObject>
    <label>Empleado</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Número de empleado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empleados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MonthlyTimeRecordControl__c.object
<CustomObject>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <label>Empleado viculado</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Registros de control mensuales</relationshipLabel>
        <relationshipName>MonthlyTimeRecordControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Registro de control mensual</label>
    <nameField>
        <displayFormat>RCM-{0000}</displayFormat>
        <label>Número de registro de control mensual</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de control mensuales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeRecordControl__c.object
<CustomObject>
    <fields>
        <fullName>EmployeeHasLeftWorkplace__c</fullName>
        <formula>IF(
(LEFT(TEXT( GeolocationOnCheckEndWorkingHours__Latitude__s ), 6) &lt;&gt; LEFT(TEXT( StartWorkingHoursGeolocation__Latitude__s ), 6)) &amp;&amp;
(LEFT(TEXT( GeolocationOnCheckEndWorkingHours__Longitude__s ), 6) &lt;&gt; LEFT(TEXT( StartWorkingHoursGeolocation__Longitude__s ), 6)) &amp;&amp; TIMENOW() = TimeEndWorkingHoursControl__c ,
TRUE,
FALSE)</formula>
        <label>Validación correcta abandono sede</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecordDate__c</fullName>
        <label>Fecha de registro</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecordedByCompany__c</fullName>
        <label>Registrado por compañía</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TimeRecordControlId__c</fullName>
        <label>Registro de control mensual</label>
        <referenceTo>MonthlyTimeRecordControl__c</referenceTo>
        <relationshipLabel>Registros de control</relationshipLabel>
        <relationshipName>TimeRecordControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isTeleworking__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Teletrabajo</label>
        <type>Checkbox</type>
    </fields>
    <label>Registro de control</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Referencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de control</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchInformEmployeeHasLeftWorkplace.cls
/**
 * @file        BatchInformEmployeeHasLeftWorkplace.apxc
 * @author      Héctor Cervera Panella
 * @date        06/12/2019
 * @description AutoScheduled batch to:
 *              Inform EmployeeHasLeftWorkplace__c according to previous and current geolocation
 */
global class BatchInformEmployeeHasLeftWorkplace implements Database.Batchable<sObject>, Database.Stateful{

    // Vars
    private List<TimeRecordControl__c> lstTimeRecToInform = new List<TimeRecordControl__c>();
    private List<TimeRecordControl__c> lstTimeRecToUpdate = new List<TimeRecordControl__c>();
    private Integer CRON_INTERVAL;
    private Integer CRON_INTERVAL_NIGHT;
	private Integer BATCH_SIZE;
	private Integer QUERY_LIMIT;
    private Date insDate = System.today();
    private DateTime insDateTime = System.now();
    private Time currTime = insDateTime.time();

    // Builder
    global BatchInformEmployeeHasLeftWorkplace(){
        CRON_INTERVAL = 10;
        BATCH_SIZE = 200;
        QUERY_LIMIT = 5000;
        CRON_INTERVAL_NIGHT = 600;
    }

    // Start
    global List<TimeRecordControl__c> start(Database.BatchableContext BC) {
        lstTimeRecToInform = new List<TimeRecordControl__c>([SELECT Id, isTeleworking__c, EndWorkingTime__c, EmployeeHasLeftWorkplace__c,  TimeRecordControlId__r.EmployeeId__r.MobilePhone__c, 
                        StartWorkingHoursGeolocation__Latitude__s, StartWorkingHoursGeolocation__Longitude__s, GeolocationOnCheckEndWorkingHours__Latitude__s, 
                        GeolocationOnCheckEndWorkingHours__Longitude__s, CheckEndWorkingHours__c, EndCheckEndWorkingHours__c, RecordedByCompany__c 
                        FROM TimeRecordControl__c
                        WHERE RecordDate__c =: insDate 
                        AND isTeleworking__c = FALSE 
                        AND CheckEndWorkingHours__c >=:currTime 
                        AND EndCheckEndWorkingHours__c <=: currTime 
                        AND EmployeeHasLeftWorkplace__c!=TRUE
                        AND EndWorkingTime__c!=NULL
                        LIMIT : QUERY_LIMIT]);
        return lstTimeRecToInform;
    }

    // Execute
    global void execute(Database.BatchableContext BC, List<TimeRecordControl__c> lstTimeRecToInform){
        if(!lstTimeRecToInform.isEmpty()){
            for(TimeRecordControl__c ins: lstTimeRecToInform){
                if(ins.StartWorkingHoursGeolocation__Latitude__s!=ins.GeolocationOnCheckEndWorkingHours__Latitude__s && 
                ins.StartWorkingHoursGeolocation__Longitude__s!=ins.GeolocationOnCheckEndWorkingHours__Longitude__s){
                    ins.EmployeeHasLeftWorkplace__c = true;
                    lstTimeRecToUpdate.add(ins);
                }
            }
        }
        if(lstTimeRecToUpdate.isEmpty()){
            update lstTimeRecToUpdate;
        }
    }

    // Finish
    global void finish(Database.BatchableContext BC){
        if (!Test.isRunningTest()) {
            DateTime currDayTime = System.now();
            System.debug(LoggingLevel.INFO,'Current DateTime is: '+currDayTime);
            Integer currHour = currDayTime.hour();
            System.debug(LoggingLevel.INFO,'Current hour is: '+currHour);

            if(currHour==23){
                scheduleMe(CRON_INTERVAL_NIGHT, BATCH_SIZE);
                System.debug(LoggingLevel.DEBUG, 'End of BatchInformEmployeeHasLeftWorkplace at: '+currHour);
            }else{
                scheduleMe(CRON_INTERVAL, BATCH_SIZE);
            }
		}
    }

    // Util methods
    private static void scheduleMe(Integer interval, Integer batchSize) {
		System.scheduleBatch(new BatchInformEmployeeHasLeftWorkplace(), Test.isRunningTest() ? 'ScheduleTestBatchInformEmployeeHasLeftWorkplace' : 'BatchInformEmployeeHasLeftWorkplace', interval, batchSize);
	}

}