src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>LinkedUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usuario vinculado</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Empleados</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Empleado</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Número de empleado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empleados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Headquarters__c.object
<CustomObject>
    <label>Sede</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sedes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MonthlyTimeRecordControl__c.object
<CustomObject>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <label>Empleado viculado</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Registros de control mensuales</relationshipLabel>
        <relationshipName>MonthlyTimeRecordControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Registro de control mensual</label>
    <nameField>
        <displayFormat>RCM-{0000}</displayFormat>
        <label>Número de registro de control mensual</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de control mensuales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeRecordControl__c.object
<CustomObject>
    <fields>
        <fullName>RecordDate__c</fullName>
        <label>Fecha de registro</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TimeRecordControlId__c</fullName>
        <label>Registro de control mensual</label>
        <referenceTo>MonthlyTimeRecordControl__c</referenceTo>
        <relationshipLabel>Registros de control</relationshipLabel>
        <relationshipName>TimeRecordControls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Registro de control</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Referencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de control</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeRecordControlController.cls
global with sharing class TimeRecordControlController {

    private static User u = [SELECT Id FROM User WHERE Id = : UserInfo.getUserId()]; // User executing code
    private static Employee__c emp = [SELECT Id, LinkedUser__r.Id FROM Employee__c WHERE LinkedUser__r.Id = : u.Id ]; // User executing code
    private static Date todayDate = Date.today();

    // Check if the employee must work today: If false display spinner, else execute employeeIsAtHeadquerts
    @AuraEnabled(cacheable=true)
    global static boolean employeeCanWork(){

        List<TimeRecordControl__c> lstTimeRec = new List<TimeRecordControl__c>([SELECT Id, EndWorkingTime__c, TimeRecordControlId__r.EmployeeId__r.LinkedUser__r.Id
                                FROM TimeRecordControl__c 
                                WHERE TimeRecordControlId__r.EmployeeId__r.LinkedUser__r.Id =: u.Id
                                AND RecordDate__c =: todayDate
                                AND EndWorkingTime__c!=null
                                LIMIT 1]);
        Boolean canWork = lstTimeRec.isEmpty() ? true: false;
        return canWork;
    }

    // Check if the employee geolocation matches any of the company headquarters
    @AuraEnabled(cacheable=true)
    public static String employeeIsAtHeadquerts(Coordinates geolocationObject){       
        List<Headquarters__c> lstHeadquarters = new List<Headquarters__c>([SELECT Name, HeadquartersGeolocation__Latitude__s, HeadquartersGeolocation__Longitude__s 
                                                                          FROM Headquarters__c
                                                                          WHERE HeadquartersGeolocation__Latitude__s =: geolocationObject.latitude
                                                                          AND HeadquartersGeolocation__Longitude__s =: geolocationObject.longitude
                                                                          LIMIT 1]);
               
        boolean checkTeleworking = lstHeadquarters.isEmpty() ? true: false;

        String strToReturn;

        if(checkTeleworking){
            strToReturn = 'Su ubicación no coincide con la de ninguna sede de la compañía. Marque la casilla de teletrabajo';
        }else{
            for(Headquarters__c sede: lstHeadquarters){
                strToReturn = 'Se encuentra usted en la sede '+sede.Name;
            }
        }

        return strToReturn;
    }

    // Get start working hours
    /*@AuraEnabled(cacheable=false)
    public static void saveNewTimeRecordControl__c(String caseToInsert){

        Case caseObject = (Case)JSON.deserialize(caseToInsert, Case.class);

        Database.SaveResult[] caseResult;
        caseResult = Database.insert(new List<Case>{caseObject}, false);
        System.debug('caseResult: ' + caseResult);

        System.debug('result: ' + caseResult);
		DmlResultWrapper resultWrap = new DmlResultWrapper(caseResult[0]);
		
        System.debug('Resultado: '+resultWrap);
		return JSON.serialize(resultWrap);
    }*/


    public class Coordinates{
        Decimal latitude;
        Decimal longitude;
    }

}